/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.epustaka.frontend;

/**
 *
 * @author mazhn
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btMenuBuku = new javax.swing.JButton();
        btMenuPeminjaman = new javax.swing.JButton();
        btMenuAnggota = new javax.swing.JButton();
        btMenuPustakawan = new javax.swing.JButton();
        btMenuTentang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 64));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ePustaka");

        btMenuBuku.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btMenuBuku.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btMenuBuku.setForeground(new java.awt.Color(255, 255, 255));
        btMenuBuku.setText("Buku");
        btMenuBuku.setToolTipText("Menu Buku");
        btMenuBuku.setBorder(null);
        btMenuBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenuBuku.setPreferredSize(new java.awt.Dimension(72, 64));
        btMenuBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuBukuActionPerformed(evt);
            }
        });

        btMenuPeminjaman.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btMenuPeminjaman.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btMenuPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btMenuPeminjaman.setText("Peminjaman");
        btMenuPeminjaman.setToolTipText("Menu Peminjaman");
        btMenuPeminjaman.setBorder(null);
        btMenuPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenuPeminjaman.setPreferredSize(new java.awt.Dimension(72, 64));
        btMenuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuPeminjamanActionPerformed(evt);
            }
        });

        btMenuAnggota.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btMenuAnggota.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btMenuAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btMenuAnggota.setText("Anggota");
        btMenuAnggota.setToolTipText("Menu Anggota");
        btMenuAnggota.setBorder(null);
        btMenuAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenuAnggota.setPreferredSize(new java.awt.Dimension(72, 64));
        btMenuAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuAnggotaActionPerformed(evt);
            }
        });

        btMenuPustakawan.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btMenuPustakawan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btMenuPustakawan.setForeground(new java.awt.Color(255, 255, 255));
        btMenuPustakawan.setText("Pustakawan");
        btMenuPustakawan.setToolTipText("Menu Pustakawan");
        btMenuPustakawan.setBorder(null);
        btMenuPustakawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenuPustakawan.setPreferredSize(new java.awt.Dimension(72, 64));
        btMenuPustakawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuPustakawanActionPerformed(evt);
            }
        });

        btMenuTentang.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btMenuTentang.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btMenuTentang.setForeground(new java.awt.Color(255, 255, 255));
        btMenuTentang.setText("Tentang");
        btMenuTentang.setToolTipText("Menu Tentang");
        btMenuTentang.setBorder(null);
        btMenuTentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMenuTentang.setPreferredSize(new java.awt.Dimension(72, 64));
        btMenuTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuTentangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMenuBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenuAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenuPustakawan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenuTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMenuBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btMenuPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btMenuAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btMenuPustakawan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btMenuTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuBukuActionPerformed
        // TODO add your handling code here:
        Buku bukuFrame = new Buku();
        bukuFrame.show();
        dispose();
    }//GEN-LAST:event_btMenuBukuActionPerformed

    private void btMenuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMenuPeminjamanActionPerformed

    private void btMenuAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuAnggotaActionPerformed
        // TODO add your handling code here:
        Anggota anggotaFrame = new Anggota();
        anggotaFrame.show();
        dispose();
    }//GEN-LAST:event_btMenuAnggotaActionPerformed

    private void btMenuPustakawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuPustakawanActionPerformed
        // TODO add your handling code here:
        Pustakawan pustakawanFrame = new Pustakawan();
        pustakawanFrame.show();
        dispose();
    }//GEN-LAST:event_btMenuPustakawanActionPerformed

    private void btMenuTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuTentangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMenuTentangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMenuAnggota;
    private javax.swing.JButton btMenuBuku;
    private javax.swing.JButton btMenuPeminjaman;
    private javax.swing.JButton btMenuPustakawan;
    private javax.swing.JButton btMenuTentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
